language: ruby
script: bundle exec rspec
deploy:
  provider: rubygems
  api_key:
    secure: OsHoXEocMnrcXkEyYw9fK2MPKQR1lISk8EGkMxm/pSEEgi1gSSTWFL+CUOg6f7nJCq7GOoXJ7pLWTItNSv+oUIIztnjo+0wdYWFUuu/HYL9c+61EoAnHrrrOPDDbp+LMA9CWNlBRwuogf0Ym7w2PmQsBU/7fP/21ZwcojODRHC+KXQwx0GcBGsQqVdPIL8jfQZWuP826QEjNzKWOkbkUxRj+xk4xLaS9RRXHb9RXKNmO+aOBllkak5YT+n30Pl2QN79mybvD9/1VMElo7LS1JNUmkyD1TXMjkYtOObSumoPeBt3+PaQP2kFEJsMZ+rOCUxu3gkMJhzF/g++UmRf0tB/MQNjyFkKOEp0Ns9IGV8pzCe+9Cj0engfnwxeGKtBNhNIzBCF69LMrSdcsi4liNY8HsAUJIdGVeC0YPkyPCew8MeD8riCLZy0BQUW4LGZj4wH231HjQ5tkvUHZHjvcyQTtJ811OZTLvlghe4IHmnq6wWiINkTgRZW1O8oQwiesnlbImWZTXqHmZj+3+/Ak1m2A9hHSjx+/YYbVAemzawE5+YQmG1Qyj200CTd7DuH6EUBAep/8KQGiz0UiaAScy7REx/zfwoRzCUa006EMkN9YRJzdCA05vAkKyS7+aEV1ONYqCOtVzdljeCEICGDeiQC5tUjsfQzZpeET0hrnWok=
